language: node_js
node_js:
- '8'
services:
  - mongodb
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - clinent/node_modules
before_install:
- npm update
- cd client
- npm install
- cd ..
install:
- npm install
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
- npm test
- cd client
- npm run test
- npm run test:coverage
- npm run build
