language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - clinent/node_modules
before_install:
- npm update
install:
- cd client/ && npm install
- npm install
script:
- npm run test:client
- npm run coverage:client
- npm run build:client
